### ISSUE TITLE
problem with DataCollection

### ISSUE THREAD

**Issue by ledarky** [PalotaCompany/cordova-plugin-honeywell-barcode-scanner#1]
Hello i've install the plugin but when i try to build it return this error

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find :DataCollection:.
  Searched in the following locations:
      file:/C:/sdk/extras/m2repository//DataCollection//DataCollection-.pom
      file:/C:/sdk/extras/m2repository//DataCollection//DataCollection-.aar
      file:/C:/sdk/extras/google/m2repository//DataCollection//DataCollection-.pom
      file:/C:/sdk/extras/google/m2repository//DataCollection//DataCollection-.aar
      file:/C:/sdk/extras/android/m2repository//DataCollection//DataCollection-.pom
      file:/C:/sdk/extras/android/m2repository//DataCollection//DataCollection-.aar
      https://jcenter.bintray.com//DataCollection//DataCollection-.pom
      https://jcenter.bintray.com//DataCollection//DataCollection-.aar
      https://maven.google.com//DataCollection//DataCollection-.pom
      https://maven.google.com//DataCollection//DataCollection-.aar
      https://repo1.maven.org/maven2//DataCollection//DataCollection-.pom
      https://repo1.maven.org/maven2//DataCollection//DataCollection-.aar
      file:/C:/Users/esco/miouzik/platforms/android/app/libs/DataCollection-.aar
      file:/C:/Users/esco/miouzik/platforms/android/app/libs/DataCollection.aar
  Required by:
      project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
(node:7160) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find :DataCollection:.
  Searched in the following locations:
      file:/C:/sdk/extras/m2repository//DataCollection//DataCollection-.pom
      file:/C:/sdk/extras/m2repository//DataCollection//DataCollection-.aar
      file:/C:/sdk/extras/google/m2repository//DataCollection//DataCollection-.pom
      file:/C:/sdk/extras/google/m2repository//DataCollection//DataCollection-.aar
      file:/C:/sdk/extras/android/m2repository//DataCollection//DataCollection-.pom
      file:/C:/sdk/extras/android/m2repository//DataCollection//DataCollection-.aar
      https://jcenter.bintray.com//DataCollection//DataCollection-.pom
      https://jcenter.bintray.com//DataCollection//DataCollection-.aar
      https://maven.google.com//DataCollection//DataCollection-.pom
      https://maven.google.com//DataCollection//DataCollection-.aar
      https://repo1.maven.org/maven2//DataCollection//DataCollection-.pom
      https://repo1.maven.org/maven2//DataCollection//DataCollection-.aar
      file:/C:/Users/esco/miouzik/platforms/android/app/libs/DataCollection-.aar
      file:/C:/Users/esco/miouzik/platforms/android/app/libs/DataCollection.aar
  Required by:
      project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
    at ChildProcess.whenDone (C:\Users\esco\miouzik\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:7160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ledarky** [comment]
i've found a solution
copy DataCollection.jar in platforms/app/android/libs directory
but do you have a best solution for me please ?

**Comment by ledarky** [comment]
this plugin doesn't work don't spend your time to install it !

**Comment by KholofeloMoyaba** [comment]
@ledarky thanks for your feedback. Perhaps try opening your project on Android Studio and make sure that the .aar in the libs folder is linked.?
On our side, we've tested successfully on CK75.
We were also building on Unix and not Windows.
